id = "gafelson"
name = "gafelson Theme"
version = "1.1.1"
schema_version = 1
authors = ["Soheil Fouladvandi <@gafelson>"]
description = "An evolving theme pack for Zed: dark roots, vivid variants"
repository = "https://github.com/gafelson/zed-theme"
